services:
  - type: web
    name: video_processor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers=1 --bind=0.0.0.0:5000
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MY_CHAT_ID
        sync: false
